[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaCustom.variants.design]
capital-a = "straight-top-serifed"
capital-b = "standard-bilateral-serifed"
capital-c = "unilateral-serifed"
capital-d = "standard-bilateral-serifed"
capital-e = "top-left-serifed"
capital-f = "top-left-serifed"
capital-g = "toothed-serifless-capped"
capital-h = "top-left-serifed"
capital-i = "serifed"
capital-j = "serifed"
capital-k = "straight-top-left-serifed"
capital-l = "serifed"
capital-m = "hanging-motion-serifed"
capital-n = "standard-motion-serifed"
capital-p = "closed-motion-serifed"
capital-q = "crossing-curly-tailed"
capital-r = "straight-top-left-serifed"
capital-s = "unilateral-serifed"
capital-t = "motion-serifed"
capital-u = "tailed-motion-serifed"
capital-v = "straight-motion-serifed"
capital-w = "straight-motion-serifed"
capital-x = "straight-motion-serifed"
capital-y = "straight-serifed"
capital-z = "straight-top-serifed"
a = "double-storey-serifed"
b = "toothed-motion-serifed"
c = "unilateral-serifed"
d = "toothed-top-serifed"
e = "rounded"
f = "serifless-crossbar-at-x-height"
g = "double-storey"
h = "straight-motion-serifed"
i = "serifed"
j = "serifed"
k = "straight-top-left-serifed"
l = "zshaped"
m = "top-left-serifed"
n = "straight-motion-serifed"
p = "eared-serifed"
q = "straight-bottom-serifed"
r = "top-serifed"
s = "unilateral-serifed"
t = "bent-hook-short-neck"
u = "tailed-serifed"
v = "straight-motion-serifed"
w = "straight-motion-serifed"
x = "straight-motion-serifed"
y = "straight-motion-serifed"
z = "straight-top-serifed"
long-s = "bent-hook-middle-serifed"
eszet = "sulzbacher-middle-serifed"
lower-eth = "curly-bar"
lower-thorn = "motion-serifed"
lower-alpha = "barred-tailed-serifed"
capital-gamma = "top-right-serifed"
capital-delta = "curly"
lower-delta = "flat-top"
lower-iota = "serifed-diagonal-tailed"
capital-lambda = "straight-base-serifed"
lower-lambda = "straight-turn"
lower-mu = "toothed-motion-serifed"
lower-xi = "flat-top"
lower-pi = "tailed"
lower-tau = "diagonal-tailed"
lower-chi = "chancery"
cyrl-capital-zhe = "symmetric-connected"
cyrl-zhe = "symmetric-touching"
cyrl-capital-ze = "unilateral-inward-serifed"
cyrl-ze = "unilateral-serifed"
cyrl-capital-ka = "straight-top-left-and-bottom-right-serifed"
cyrl-ka = "curly-top-left-serifed"
cyrl-el = "tailed"
cyrl-em = "slanted-sides-hanging-serifed"
cyrl-en = "top-left-serifed"
cyrl-er = "earless-corner-serifed"
cyrl-capital-u = "straight-serifed"
cyrl-u = "straight-motion-serifed"
cyrl-ef = "top-serifed"
cyrl-che = "tailed"
cyrl-yeri = "round"
cyrl-yery = "corner-tailed"
cyrl-capital-ya = "straight-motion-serifed"
cyrl-ya = "straight-serifed"
zero = "reverse-slashed"
one = "no-base"
two = "straight-neck-serifed"
three = "flat-top-serifed"
four = "semi-open-serifed"
five = "upright-arched-serifless"
six = "open-contour"
seven = "straight-serifless-crossbar"
eight = "two-circles"
nine = "open-contour"
tittle = "square"
diacritic-dot = "square"
punctuation-dot = "square"
tilde = "high"
asterisk = "turn-hex-high"
underscore = "low"
caret = "high"
ascii-grave = "straight"
ascii-single-quote = "straight"
paren = "large-contour"
brace = "straight"
guillemet = "curly"
number-sign = "upright-open"
ampersand = "closed"
at = "fourfold"
dollar = "through"
cent = "bar-interrupted"
percent = "rings-segmented-slash"
bar = "force-upright"
question = "corner"
pilcrow = "low"
partial-derivative = "curly-bar"
micro-sign = "toothed-motion-serifed"
lig-ltgteq = "slanted"
lig-neq = "more-slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"
lig-plus-chain = "without-notch"
lig-double-arrow-bar = "without-notch"
lig-single-arrow-bar = "without-notch"

[buildPlans.IosevkaCustom.ligations]
inherits = "dlig"
